swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /account/{userId}:
    get:
      security: 
        - Bearer: []
      tags: 
        - Account Module
      summary: Account information API 
      description: API to get all account resume
      parameters:
        - in: path
          name: userId
          type: number
          required: true
          description: user Id to obtain all the accounts concerning him
      produces:
        - application/json
      responses: 
        '200': 
          description: Acounts recovered successfully
          schema:
            $ref: '#/definitions/AccountResume'
  /transaction/{accountId}:
    get:
      security: 
        - Bearer: []
      tags: 
        - Transaction Module
      summary: Transaction get all API
      description: API to obtain all transactions for the current month
      parameters: 
        - in: path
          name: accountId
          type: number
          required: true
          description: Id for account to get all transactions
      produces: 
       - application/json
      responses:
        '200':
          description: Transactions recovered successfully
          schema:
            $ref: '#/definitions/TransactionAccount'
        '400': 
          description: 'Invalid Fields'
        '500':
          description: Internal Server Error
  /transaction/category/{id}:
    put:
      security: 
        - Bearer: []
      tags: 
       - Transaction Module
      summary: Transaction category API
      description: API for edit category of transaction
      parameters: 
        - in: path
          name: id
          type: number
          required: true
          description: ID of the transaction to update
        - in: body
          name: body
          description: Update transaction category 
          required: true
          schema: 
            $ref: '#/definitions/TransactionCategory'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction category retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transaction/note/{id}:
    put: 
      security: 
        - Bearer: []
      tags: 
        - Transaction Module
      summary: Transaction note API
      description: API to edit note to a transaction
      parameters: 
        - in: path
          name: id
          type: number
          required: true
          description: ID of the transaction to update
        - in: body
          name: body
          description: Add note to a transaction
          required: true
          schema: 
            $ref: '#/definitions/TransactionNote'
      produces: 
        - application/json
      responses:
        '200':
          description: Transaction note retrieved successully
          schema: 
            $ref: '#/definitions/TransactionNote'
        '400': 
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  AccountResume: 
    type: object
    properties: 
      currentAccount:
        type: object
        properties:
          id:
            type: string
          balance: 
            type: string
      savingAccount: 
        type: object
        properties:
          id:
            type: string
          balance: 
            type: string
      creditCard:
        type: object
        properties:
          id:
            type: string
          balance: 
            type: string
  TransactionAccount:
    type: object
    properties: 
      accountName:
        type: object
        properties:
          id:
            type: string
          balance: 
            type: string
          transaction:
            type: array
            items: 
              type: object
              properties:
                id: 
                  type: string
                Details : 
                  type: object
                  properties:
                   Type: 
                    type: string
                   Category:
                    type: string
                   Note:
                    type: string
                Date:
                  type: string
                Description: 
                  type: string
                Amount:
                 type: string
                Balance: 
                  type: string
  TransactionCategory:
    type: object 
    properties:
      Category: 
        type: string
  TransactionNote:
    type: object 
    properties:
      Note: 
        type: string